See ph slope
Open-Acidification/TankController pull request #134
Opened 2021-05-06 16:26 UTC by eucalvo

and template class for PID on/off

2021-05-06 17:58 UTC, jgfoster requested changes
Good work! I have a couple small suggestion...

2021-05-06 17:58 UTC, jgfoster commented on src/UIState/MainMenu.cpp
> +      this->setNextState((UIState *)new SetPIDOnOff(tc));
We have a new code style checker that is stricter about some things that we have been in the past. This line should be revised as follows:
`   this->setNextState(static_cast<UIState *>(new SetPIDOnOff(tc)));`
Eventually all the other "C-style type casts" should be converted to "C++-style type casts" but for now I'm just doing them one-at-a-time as the tests complain.

2021-05-06 17:58 UTC, jgfoster commented on src/UIState/SeePHSlope.cpp
> +  LiquidCrystal_TC::instance()->writeLine("requesting slope", 1);
See #135.

2021-05-08 00:41 UTC, prestoncarman approved these changes
LGTM

2021-05-08 00:43 UTC, merged