Serial out temp
Open-Acidification/TankController pull request #150
Opened 2021-05-12 20:59 UTC by eucalvo

2021-05-12 23:04 UTC, jgfoster requested changes
It looks like we have a couple failing tests. You should pull from main to get the latest so you can observe the same test failures. To get rid of the RTC warning you could clear the output buffer just before running the test. Then, you need to add the date/time line to your expected output.

2021-05-13 02:01 UTC, jgfoster approved these changes
LGTM

2021-05-13 03:01 UTC, jgfoster commented
Fixed #146.

2021-05-13 03:28 UTC, prestoncarman requested changes

2021-05-13 03:28 UTC, prestoncarman commented on test/TestTemperatureControl.cpp
> +  assertEqual("2021-01-15 01:48:55\r\nchiller on after 31000 ms\r\n", state->serialPort[0].dataOut);
We should also have a test print for when the chiller turns off.

2021-05-13 03:28 UTC, prestoncarman commented on test/TestTemperatureControl.cpp
> +  assertEqual("2021-01-15 01:48:24\r\nheater on after 0 ms\r\n", state->serialPort[0].dataOut);
We should also have a test print for when the heater turns off.

2021-05-13 03:28 UTC, prestoncarman commented on src/Devices/PHControl.h
> +  unsigned long lastSwitchMS = 0;
This seems out of place since you are only changing temperature.

Remove this line and include it in the ph change.

2021-05-16 21:05 UTC, prestoncarman approved these changes
LGTM

2021-05-16 21:07 UTC, jgfoster approved these changes

2021-05-16 21:08 UTC, merged