Temp calibration
Open-Acidification/TankController pull request #176
Opened 2021-06-03 03:21 UTC by eucalvo

fix issue #174

2021-06-03 04:28 UTC, jgfoster approved these changes
Note that this addresses two issues:
- Fix problem with temperature calibration (#174)
- Show "current" values for time when setting new values (#164)

2021-06-03 19:14 UTC, jgfoster requested changes
Per discussion with @prestoncarman

2021-06-03 19:14 UTC, jgfoster commented on src/Devices/TempProbe_TC.h
>    uint16_t getResistance() {
Replace this with `getUncorrectedRunningAverage()`.

2021-06-03 19:14 UTC, jgfoster commented on src/UIState/TemperatureCalibration.cpp
> +  float uncorrectedAverage = pProbe->getRunningAverage() - pProbe->getCorrection();
Use `getUncorrectedRunningAverage()`.

2021-06-03 23:37 UTC, jgfoster approved these changes

2021-06-06 03:30 UTC, prestoncarman approved these changes
LGTM

2021-06-06 13:47 UTC, merged