Fix #117
Open-Acidification/TankController pull request #180
Opened 2021-06-03 23:24 UTC by Paydenb

Fix problem#117:
Now there is a UI that displays if PID is on or off

2021-06-03 23:36 UTC, jgfoster requested changes
Delete one line...

2021-06-03 23:36 UTC, jgfoster commented on src/UIState/SeePIDConstants.h
> +//   void loadSlope(uint16_t line);
If we find we don't need this file (things work with it commented out), let's remove the line.

2021-06-04 01:04 UTC, jgfoster commented on src/UIState/SeePIDConstants.h
> +//   void loadSlope(uint16_t line);
Note also that this line fails the formatting test, so when it is removed we should have passing tests!

2021-06-07 21:01 UTC, jgfoster approved these changes

2021-06-07 22:33 UTC, prestoncarman approved these changes
LGTM

2021-06-07 22:46 UTC, merged

2021-06-10 05:10 UTC, prestoncarman commented
@all-contributors please add @Paydenb for code