Report C for calibration mode
Open-Acidification/TankController pull request #198
Opened 2021-06-10 04:04 UTC by eucalvo

report C to sd and to google sheets

2021-06-10 04:25 UTC, jgfoster requested changes

2021-06-10 04:25 UTC, jgfoster commented on test/PushingBoxTest.cpp
> +  pPushingBox->getClient()->pushToReadBuffer('A');
This line isn't needed since you aren't looking at the serial port log.

2021-06-10 04:25 UTC, jgfoster commented on test/SDTest.cpp
> +
Now we need a test similar to the one above that replaces the temperature and pH with 'C' during calibration.

2021-06-11 21:27 UTC, prestoncarman approved these changes
LGTM

2021-06-11 22:57 UTC, jgfoster approved these changes

2021-06-11 22:57 UTC, merged