Sine wave pH
Open-Acidification/TankController pull request #269
Opened 2021-12-03 17:06 UTC by eucalvo

2021-12-09 00:27 UTC, jgfoster approved these changes

2021-12-09 00:47 UTC, prestoncarman requested changes
The main question is how to deal with naming pH variables and files. I think we need to be more consistent. We seem to use "pH", "PH", and "Ph". I can see arguments for all of these, but in most cases I think that "Ph" is probably the correct answer.
Thought?

2021-12-09 00:47 UTC, prestoncarman commented on src/Devices/EEPROM_TC.cpp
> +uint16_t EEPROM_TC::getPHSetType() {
"Ph" or "PH"? Lets be consistent and make it always "Ph" in the function names.

2021-12-09 00:47 UTC, prestoncarman commented on src/Devices/EEPROM_TC.cpp
> +void EEPROM_TC::setPHSetType(uint16_t value) {
"Ph" or "PH"? Lets be consistent and make it always "Ph" in the function names.

2021-12-09 00:47 UTC, prestoncarman commented on src/Devices/EEPROM_TC.h
> +  float getPHDelay();          // not used
"Ph" or "PH"? Lets be consistent and make it always "Ph" in the function names. Update for the whole file.

2021-12-09 00:47 UTC, prestoncarman commented on test/MenuTest.cpp
> +// 2 goes up in the menu
I think this comment would be nice to have as a multiline comment associated with the function.

```c++
/**
 * 2 goes up in the menu
 * ...
 */
unittest(MainMenu) {
```

This should help it to show up with function documentation.

2021-12-09 04:05 UTC, jgfoster commented
The chemists and biologists use "pH" as the proper designation, but that doesn't fit very well with camelCase. So, consistency is good and Ph fits so I'd be inclined to go with that...

2021-12-20 01:24 UTC, prestoncarman approved these changes

2021-12-22 22:53 UTC, jgfoster approved these changes

2021-12-22 22:54 UTC, merged