add sine to temp
Open-Acidification/TankController pull request #298
Opened 2022-03-08 18:28 UTC by eucalvo

2022-03-08 19:11 UTC, jgfoster requested changes

2022-03-08 19:11 UTC, jgfoster commented on src/UIState/SetTempWithSine.cpp
> +    snprintf_P(output0, sizeof(output0), (PGM_P)F("New Temp=%i.%i"), (int)values[0],
Need `%i.03%i` here and below...

2022-03-08 19:13 UTC, jgfoster approved these changes

2022-03-09 22:09 UTC, jgfoster approved these changes

2022-03-10 16:18 UTC, prestoncarman approved these changes
LGTM

2022-03-10 16:20 UTC, merged