See temperature
Open-Acidification/TankController pull request #315
Opened 2022-06-17 22:19 UTC by eucalvo

2022-07-11 02:46 UTC, jgfoster commented
Eliam, thanks for merging our latest updates in main to your. That will make it much easier to review this!

2022-07-11 20:12 UTC, jgfoster requested changes
Let's talk about the failing tests.

2022-07-11 20:12 UTC, jgfoster commented on src/UIState/SeeVersion.cpp
> +  // const char* version = TankController::instance()->version();
Remove commented-out code.

2022-07-11 20:12 UTC, jgfoster commented on test/MenuTest.cpp
> +  delay(200);  // going back to idle screen requires this
I think that the delay() should not be needed any more.

2022-07-11 20:12 UTC, jgfoster commented on test/PHControlTest.cpp
> +  delay(7);
Can we try again without the delay()?

2022-07-20 17:26 UTC, eucalvo commented
> 

By failing tests, do you mean the memory space available one?

2023-01-24 04:47 UTC, jgfoster commented
@eucalvo, could you contact me at WWU and give me a current email address? Thanks.

2023-03-05 04:51 UTC, jgfoster commented
I think this has been superseded by later changes.

2023-03-05 04:51 UTC, closed without merging