Libraries and clearing display
Open-Acidification/TankController pull request #378
Opened 2023-03-09 22:40 UTC by Suocesky

With the repository merge, some extra libraries were needed and installed. 
Instances of = Tank('', '') have been removed and been replaced with either a clearTank function that sets the current tank to empty, or a bool function checking if the current tank is empty or not.
The display and tank name header on the web page will now clear themselves when the current tank is deleted from the tank list.

2023-03-09 23:52 UTC, jgfoster requested changes

2023-03-09 23:52 UTC, jgfoster commented on extras/webClient/lib/components/app_drawer.dart
> +              onPressed: () {
Is this proper format?

2023-03-09 23:52 UTC, jgfoster commented on extras/webClient/lib/model/app_data.dart
>      _tankList.remove(tank);
Only clear and refresh if current tank is displayed.

2023-03-10 00:17 UTC, jgfoster approved these changes

2023-03-10 00:17 UTC, jgfoster commented on extras/webClient/lib/components/app_drawer.dart
> +              onPressed: () {
Looks good!

2023-03-10 00:17 UTC, jgfoster commented on extras/webClient/lib/model/app_data.dart
>      _tankList.remove(tank);
Looks good!

2023-03-10 16:41 UTC, prestoncarman approved these changes

2023-03-10 16:42 UTC, merged