PHProbe part1
Open-Acidification/TankController pull request #67
Opened 2021-03-25 05:52 UTC by eucalvo

Unfinished wrapper to PHProbe class

2021-03-25 19:12 UTC, jgfoster requested changes
Let's talk about a minor change to the API.

2021-03-25 19:12 UTC, jgfoster commented on src/TankControllerLib.cpp
> +  String string = Serial1.readStringUntil(13);  // read the string until we see a <CR>
Let's modify this to move the read into the PHProbe class.

2021-03-26 20:22 UTC, prestoncarman approved these changes
LTGM

2021-03-26 20:31 UTC, jgfoster approved these changes
LGTM

2021-03-26 20:32 UTC, merged