Ph calibration: midpoint, lowpoint, highpoint
Open-Acidification/TankController pull request #95
Opened 2021-04-22 20:51 UTC by eucalvo

2021-04-22 21:17 UTC, jgfoster requested changes
Just a couple lines of commented-out code (as well as whatever spelling or other tests remain).

2021-04-22 21:17 UTC, jgfoster commented on src/UIState/MainMenu.cpp
> +    // case SET_CALIBRATION_CLEAR:
Since this is part of MainMenu we should probably implement at least a stub that does nothing.

2021-04-22 21:18 UTC, jgfoster commented
Rather than using `sprint()` we should use `snprintf()`. See other examples in the code.

2021-04-25 16:23 UTC, jgfoster commented on src/UIState/MainMenu.cpp
> +    // case SET_CALIBRATION_CLEAR:
See #96.

2021-04-25 17:22 UTC, jgfoster approved these changes
I've addressed the issues I raised.

2021-04-25 18:39 UTC, prestoncarman approved these changes
LGTM

2021-04-25 18:42 UTC, merged